"use client";

import { useEffect, useState } from "react";
import { ArrowDown, ArrowRight, Banknote, Building2, Car, Check, ChevronDown, CircleDollarSign, FileCheck2, MapPin, Menu, MessageCircle, ShieldCheck, Smartphone, X } from "lucide-react";
import { WhatsAppButton } from "../components/WhatsAppButton";

const faqs = [
  ["Do you provide the loans directly?", "No. This website provides information and connects interested individuals with loan representatives. Loan approval and financing are handled directly by the respective lender."],
  ["How much can I borrow?", "Financing options advertised may range from KES 50,000 up to KES 10,000,000, subject to eligibility, collateral valuation and lender assessment."],
  ["Where are title deed loans available?", "The title deed financing option is intended for eligible applicants and properties within Nairobi and Kiambu."],
  ["Are logbook loans available outside Nairobi?", "Yes. Logbook financing information is available for eligible applicants across Kenya."],
  ["Is loan approval guaranteed?", "No. Approval is not guaranteed. The lender determines eligibility, loan amount, terms and approval after completing its assessment."],
  ["Do I submit my documents through this website?", "No. The website does not collect collateral documents or process loan applications. Contact the loan representative through WhatsApp for next steps."],
  ["What interest rate will I pay?", "Interest rates, fees and repayment terms depend on the lender and the specific financing arrangement. Confirm all costs and terms directly with the lender before accepting an offer."],
];

function Brand() { return <a href="#home" className="brand"><span className="brand-mark"><Building2 size={21}/></span><span><b>FinCap<span>Kenya</span></b><small>SECURED FINANCING ADVISORY</small></span></a>; }
function SectionTitle({eyebrow, title, copy}:{eyebrow:string;title:string;copy?:string}) { return <div className="section-title"><span>{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const nav = [["Loan Options","#loan-options"],["How It Works","#how-it-works"],["Requirements","#requirements"],["FAQ","#faq"]];
  useEffect(() => {
    const items = document.querySelectorAll<HTMLElement>("[data-reveal]");
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); }
    }), { threshold: 0.12 });
    items.forEach((item) => observer.observe(item));
    return () => observer.disconnect();
  }, []);
  return <>
    <header className="navbar"><div className="nav-inner"><Brand/><nav>{nav.map(([n,h])=><a key={n} href={h}>{n}</a>)}</nav><div className="nav-actions"><WhatsAppButton label="Get a Loan"/><button className="menu" aria-label="Toggle menu" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div></div>{menuOpen&&<div className="mobile-menu"><a href="#home" onClick={()=>setMenuOpen(false)}>Home</a>{nav.map(([n,h])=><a key={n} href={h} onClick={()=>setMenuOpen(false)}>{n}</a>)}</div>}</header>
    <main>
      <section id="home" className="hero"><div className="container hero-grid"><div className="hero-copy hero-intro"><div className="eyebrow"><i/> Secured financing options • Kenya</div><h1>Access Financing From <em>KES 50,000</em> to <em>KES 10 Million</em></h1><p>Explore loan options secured against eligible title deeds and motor vehicle logbooks. Connect directly with a loan representative through WhatsApp to discuss your financing needs.</p><div className="hero-buttons"><WhatsAppButton label="Get a Loan on WhatsApp"/><a className="outline-button" href="#loan-options">Explore Loan Options <ArrowDown size={18}/></a></div><div className="notice"><ShieldCheck size={19}/><p><b>Important:</b> We connect you with loan representatives. Loan approval, terms and eligibility are determined by the respective lender.</p></div><div className="stats"><div><b>50K – 10M</b><span>KES financing range</span></div><div><b>2</b><span>Collateral options</span></div><div><b>Direct</b><span>WhatsApp assistance</span></div></div></div><div className="hero-visual"><div className="visual-card"><figure><img src="/images/property.png" alt="Modern Nairobi property"/><figcaption>Nairobi & Kiambu title deeds</figcaption></figure><figure><img src="/images/vehicle.png" alt="Premium SUV in Kenya"/><figcaption>Nationwide logbook coverage</figcaption></figure></div><div className="review-chip"><span><FileCheck2 size={22}/></span><div><b>Clear next steps</b><small>Discuss requirements directly</small></div></div></div></div></section>
      <section className="range-section"><div className="container scroll-reveal" data-reveal><div className="range-head"><SectionTitle eyebrow="FINANCING RANGE" title="KES 50K → KES 10M" copy="Your actual financing amount depends on your collateral, eligibility, valuation and the lender's assessment."/></div><div className="range-line"><span className="dot start"/><div/><span className="dot end"/></div><div className="range-labels"><b>KES 50,000<small>Starting range</small></b><b>KES 10,000,000<small>Potential maximum</small></b></div></div></section>
      <section id="loan-options" className="section"><div className="container scroll-reveal" data-reveal><SectionTitle eyebrow="FINANCING OPTIONS" title="Choose the Financing Option That Fits You" copy="Explore options based on the asset you have available. Every offer is subject to lender assessment."/><div className="loan-grid"><LoanCard type="title" icon={<Building2/>} title="Title Deed Secured Loans" location="Nairobi & Kiambu" image="/images/property.png" items={["Valid title deed","Property within eligible areas","Identification documents","Additional lender requirements may apply"]}/><LoanCard type="logbook" icon={<Car/>} title="Logbook Secured Loans" location="Available Countrywide" image="/images/vehicle.png" items={["Valid motor vehicle logbook","Identification documents","Vehicle valuation/inspection may be required","Additional lender requirements may apply"]}/></div></div></section>
      <section id="how-it-works" className="process"><div className="container scroll-reveal" data-reveal><SectionTitle eyebrow="HOW IT WORKS" title="A clear path to the right conversation"/><div className="steps">{[["01","Choose Your Loan Option","Select between title deed and logbook financing."],["02","Check the Requirements","Review the basic eligibility and collateral requirements."],["03","Talk to a Loan Representative","Click Get the Loan and continue the conversation on WhatsApp."],["04","Complete the Lender's Process","The lender handles checks, valuation, documentation, approval and terms."]].map(([num,t,c])=><div className="step" key={num}><span>{num}</span><h3>{t}</h3><p>{c}</p></div>)}</div><p className="process-note"><ShieldCheck size={18}/> This website does not process or approve loans.</p></div></section>
      <section className="section eligibility"><div className="container eligibility-grid"><div><SectionTitle eyebrow="ELIGIBILITY & LOCATION" title="Where Can You Apply?" copy="The financing option and the location of your collateral help determine the right path."/><div className="location-row"><MapPin/><div><b>Title deed financing</b><span>Nairobi & Kiambu</span><p>Intended for eligible properties and applicants within these counties.</p></div></div><div className="location-row"><MapPin/><div><b>Logbook financing</b><span>Across Kenya</span><p>Available to eligible applicants throughout Kenya.</p></div></div></div><div className="advisor"><img src="/images/advisor.png" alt="Financial consultant"/><div><span>DIRECT SUPPORT</span><h3>Have a question before you begin?</h3><p>Chat with a representative to understand which financing option may suit your situation.</p><WhatsAppButton label="Talk on WhatsApp"/></div></div></div></section>
      <section id="requirements" className="requirements"><div className="container"><SectionTitle eyebrow="REQUIREMENTS" title="What You May Need" copy="Requirements may vary depending on the lender, loan amount and your circumstances."/><div className="requirements-grid"><Requirement title="For title deed financing" icon={<Building2/>} items={["Valid identification","Valid title deed","Property information","Proof of ownership and required documentation","Property valuation where applicable","Any additional documents requested by the lender"]}/><Requirement title="For logbook financing" icon={<Car/>} items={["Valid identification","Original or valid motor vehicle logbook","Vehicle information","Vehicle inspection or valuation where applicable","Proof of ownership","Any additional documents requested by the lender"]}/></div></div></section>
      <section className="section"><div className="container"><SectionTitle eyebrow="WHY CONTACT US" title="Helpful information. Direct connection."/><div className="benefits">{[[<CircleDollarSign/>,"Flexible Financing Options","Explore options based on different collateral types."],[<Smartphone/>,"Direct WhatsApp Assistance","Speak directly with a loan representative."],[<FileCheck2/>,"Clear Process","Understand the basic requirements before starting."],[<Banknote/>,"Nationwide Logbook Coverage","Logbook financing information is available across Kenya."]].map(([icon,t,c])=><div className="benefit" key={t as string}><span>{icon}</span><h3>{t as string}</h3><p>{c as string}</p></div>)}</div></div></section>
      <section className="contact"><div className="container"><div className="contact-card"><span>DIRECT WHATSAPP CONNECTION</span><h2>Ready to Discuss Your Financing Options?</h2><p>Connect with a loan representative on WhatsApp and discuss your requirements directly.</p><div><WhatsAppButton loanType="titleDeed" label="Discuss Title Deed Loan"/><WhatsAppButton loanType="logbook" label="Discuss Logbook Loan" className="light"/></div></div></div></section>
      <section id="faq" className="section faq"><div className="container narrow"><SectionTitle eyebrow="TRANSPARENT ANSWERS" title="Frequently Asked Questions"/><div>{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<ChevronDown size={20}/></summary><p>{a}</p></details>)}</div></div></section>
    </main><footer><div className="container footer-grid"><div><Brand/><p>Connecting individuals with information about available financing options in Kenya.</p></div><div><b>Explore</b><a href="#loan-options">Loan Options</a><a href="#how-it-works">How It Works</a><a href="#requirements">Requirements</a><a href="#faq">FAQ</a></div><div><b>Important notice</b><p>This website is an informational and lead-generation platform and is not a lender. We do not guarantee loan approval, loan amounts, interest rates or repayment terms. Financing decisions are made by the respective lender based on its own eligibility criteria and assessment.</p></div></div><div className="container copyright">© 2026 FinCap Kenya. All rights reserved.</div></footer><div className="mobile-cta"><WhatsAppButton label="Get a Loan"/></div>
  </>;
}

function LoanCard({type,icon,title,location,image,items}:{type:"title"|"logbook";icon:React.ReactNode;title:string;location:string;image:string;items:string[]}) { const titleDeal = type === "title"; return <article className="loan-card"><div className="loan-image"><img src={image} alt=""/><span>{icon}</span></div><div className="loan-content"><div className="loan-top"><div><span className="type-label">{titleDeal ? "PROPERTY COLLATERAL" : "VEHICLE COLLATERAL"}</span><h3>{title}</h3></div><b className="amount">KES 50K – 10M</b></div><span className="location"><MapPin size={14}/>{location}</span><p>Financing may be available to eligible applicants using qualifying {titleDeal ? "property" : "motor vehicle logbook"} as collateral.</p><ul>{items.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><WhatsAppButton loanType={titleDeal?"titleDeed":"logbook"} label={titleDeal?"Get Title Deed Loan":"Get Logbook Loan"}/></div></article>; }
function Requirement({title,icon,items}:{title:string;icon:React.ReactNode;items:string[]}) { return <article className="requirement"><div className="req-icon">{icon}</div><h3>{title}</h3><ul>{items.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul></article>; }
